### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by christaikobo** [chenhw2/luci-app-shadowsocksr#1]
我看到相关的shadowsocksr-libev for openwrt里面的编译说明有坑啊

git clone https://github.com/chenhw2/openwrt-shadowsocks.git package/feeds/shadowsocks-libev
make package/feeds/shadowsocksr-libev/compile V=99

这两行不对应所以编译失败啊
上面改成shadowsocksr就成功了

**Comment by honwen** [comment]
Fixed and Thanks

https://github.com/chenhw2/openwrt-shadowsocksr/commit/37e916bd0795936d59e3868f85547db049641a9a
