### ISSUE TITLE
Problem-DNS decteted, restarting shadowsocksr...

### ISSUE THREAD

**Issue by Iy204** [chenhw2/luci-app-shadowsocksr#10]
如何检测具体是什么问题呢，一直在频繁的重启。

**Comment by honwen** [comment]
获取不到 google.com 的ip, 检查一下dnsmasq是不是有配置问题 or 网络是不是有问题

**Comment by Iy204** [comment]
我编译装了个新版的提示是这样的。
Problem decteted, restarting shadowsocksr
我也觉得是网络问题，这个移动网络总是这样挂掉SSR。
找不出是什么问题，挂掉的时候我也有SSH上去DIG检查chinadns 解析很正常。
我用的是chinaDNS路由表模式

**Comment by honwen** [comment]
那就换个服务器再试试，移动是比较挑服务器的了
