### ISSUE TITLE
1.9.0.3啟動不起來

### ISSUE THREAD

**Issue by ctw8989** [chenhw2/luci-app-shadowsocksr#11]
Thu Jan 25 21:21:52 2018 daemon.err uhttpd[2337]: sh: /etc/init.d/shadowsocksr: line 116: syntax error: unexpected "}" (expecting "done")
Thu Jan 25 21:21:52 2018 daemon.err uhttpd[2337]: /etc/rc.common: /etc/init.d/shadowsocksr: line 116: syntax error: unexpected "}" (expecting "done")

![default](https://user-images.githubusercontent.com/16351166/35391683-546fc44e-021a-11e8-957c-389ef7864e0d.JPG)

**Comment by honwen** [comment]
PLZ git pull and recompile
