### ISSUE TITLE
restart shadowsocksr needs 2 mintues on the newest op-turnk

### ISSUE THREAD

**Issue by jack338c** [chenhw2/luci-app-shadowsocksr#16]
Dear Chen
I found it will takes at least 2 mintues for restarting shadowsocksr after upgrade to the newest openwrt-trunk
Could you check it out later

thanks

Jack

**Comment by honwen** [comment]
Check Later

**Comment by jack338c** [comment]
@chenhw2 
OK,Great !

**Comment by honwen** [comment]
Can not reproduce with https://github.com/openwrt/openwrt/commit/e261c8b76407ebd2d8289e3522bd02e5bd6e8552

**Comment by jack338c** [comment]
@chenhw2 thanks for your reply
So it can not be solved for the moment? Or it can be if I apply the patch?

**Comment by honwen** [comment]
@jack338c update openwrt to latest and try again

**Comment by jack338c** [comment]
@chenhw2 
OK, I got it
many thanks!
