### ISSUE TITLE
direct list function may have problem

### ISSUE THREAD

**Issue by jack338c** [chenhw2/luci-app-shadowsocksr#19]
Here are my steps

1 add bitz.com under bitautoimg.com to direct  in /etc/dnsmasq-extra.d
2 try restart dnsmasq-extra or reboot router
3 found  ipset=/bitz.com/ss_spec_dst_bp and ipset=/bitz.com/ssr_spec_dst_bp at direct.conf in /tmp/dnsmasq.d

but it dose not work,I can't open bitz.com
custom function is ok

:clinking_glasses:

**Comment by honwen** [comment]
restart dnsmasq and clean dns cache at Ur computer

**Comment by jack338c** [comment]
I did it and even reboot PC or use a new pc,but still get failed
