### ISSUE TITLE
openwrt nightly 问题

### ISSUE THREAD

**Issue by smaller09** [chenhw2/luci-app-shadowsocksr#20]
openwrt nightly 2020/1/2
系统界面出现错误

/usr/lib/lua/luci/template.lua:39: Failed to load template 'admin_status/syslog'.
Error while parsing template '/usr/lib/lua/luci/view/admin_status/syslog.htm':
No such file or directory
stack traceback:
	[C]: in function 'n'
	/usr/lib/lua/luci/template.lua:39: in function '__init__'
	/usr/lib/lua/luci/util.lua:44: in function 'Template'
	/usr/lib/lua/luci/template.lua:13: in function 'render'
	/usr/lib/lua/luci/controller/shadowsocksr.lua:53: in function </usr/lib/lua/luci/controller/shadowsocksr.lua:49>

**Comment by honwen** [comment]
redirect to https://github.com/honwen/luci-app-shadowsocksr/issues/21
