### ISSUE TITLE
SOCKS5 Proxy & Port Forward Not updated in Luci . . .

### ISSUE THREAD

**Issue by M33FT** [chenhw2/luci-app-shadowsocksr#22]
Thank you for releasing this proxy.
I've long been compiling the different versions you put up and installing them on my own devices.
Everything is working great so far. But recently after installing OpenWrt 19.07.2, which was installed cleanly,
 I saw in the main ShadowsocksR panel the options SOCKS5 Proxy and Port Forward appear as "NOT RUNNING".
But all services are working correctly but these two options are not updated in appearance.
I have this problem on all of the following devices with update 19.07.2:

bcm2710 (Raspberry Pi 3)
mvebu (Linksys WRT1200AC v2 & WRT1900ACS v2)
brcm47xx (Linksys E3000)

https://i1.lensdump.com/i/jk24P1.jpg

I'm not a coder but I think there is a problem with the recent 
updates from OpenWrt to the Lua code for Luci-ShadowSocksR.
Thank you for your excellent project.
Good luck.

**Comment by honwen** [comment]
try latest commit

**Comment by M33FT** [comment]
Thankful. But I compiled the latest version, but this problem is present in all four of my devices
This is the last version I installed on my device:
luci-app-shadowsocksr_1.9.0-9_all

**Comment by M33FT** [comment]
Thanks for the quick update you released.
But the problem with the new update is still there.
The last version I compiled for my devices:

luci-app-shadowsocksr_1.9.1-1_all.ipk 

I tested the latest version on all my devices but there is still a problem I said.
Anyway thank you for your nice program.
good luck my friend.

**Comment by honwen** [comment]
try official https://github.com/shadowsocks/luci-app-shadowsocks

This repo is mostly come from that repo

M33FT <notifications@github.com>于2020年4月3日 周五17:25写道：

**Comment by M33FT** [comment]
Thanks Dude ;-)
