### ISSUE TITLE
希望改进一下SSR内网主机过滤的设定

### ISSUE THREAD

**Issue by jiawen94** [chenhw2/luci-app-shadowsocksr#3]
路由器很多人在用，然而SSR的功能只有我一个人在使用，内网设定太复杂，需要对内网的内每一个设备一一配置，每一个新连接的设备都需要配置。希望下一版本能加入代理白名单的选项，只有白名单的设备才能科学上网。

**Comment by honwen** [comment]
It can be done with current features.

1. Access Control -> Zone LAN -> Proxy Type -> Direct
2. Access Control -> LAN Hosts -> Add ( ```Host: [Ur-IP], Proxy Type: [Nomral/Global]``` )
3. Save & Apply

**Comment by jiawen94** [comment]
Thank you
