### ISSUE TITLE
希望下一版本增加均衡负载

### ISSUE THREAD

**Issue by Anyfc** [chenhw2/luci-app-shadowsocksr#4]
之前使用的是haproxy来给shadowsocks原版做均衡负载，haproxy在shadowsocksr加上混淆后没有连接，目前原版luci-app-shadowsocks已经增加了均衡负载，希望这里也能增加均衡负载。

**Comment by honwen** [comment]
```luci-app-shadowsocksr``` can not support load balancing unitl [shadowsocksr-libev](https://github.com/shadowsocksr/shadowsocksr-libev) support.

U can try [luci-app-haproxy-tcp](https://github.com/chenhw2/luci-app-haproxy-tcp)

**Comment by Anyfc** [comment]
ok，thinks
