### ISSUE TITLE
使用ChnRoute分流时，按域名指定是否走代理

### ISSUE THREAD

**Issue by Anyfc** [chenhw2/luci-app-shadowsocksr#5]
目前使用的是方法是：
新建一个/etc/dnsmasq.d目录，里面新建的文件写下：
server=/youku.com/223.6.6.6#53
ipset=/youku.com/ssr_spec_dst_bp
重启dnsmasq后可以达到 youku.com 不走代理的，优化DNS解析的目的。

现在在自定义列表里写下上面的规则后没有起到作用，那么可否可以将自定义列表custom.conf这个文件移动到/etc/dnsmasq.d 以达到同样的效果？

**Comment by honwen** [comment]
have u use [dnsmasq-extra](https://github.com/chenhw2/openwrt-dnsmasq-extra/tree/master/dnsmasq-extra), ```custom.conf``` depends on ```dnsmasq-extra```.

Ur way should solve Ur problem.

But I still recommend my package: ```dnsmasq-extra``` to optimize DNS.

**Comment by Anyfc** [comment]
使用的就是dnsmasq-extra

**Comment by honwen** [comment]
没有起到作用是指？ChnRoute分流时，youku本来就不会走代理

**Comment by Anyfc** [comment]
除了优化DNS外，我还想某几个国外域名不走代理。
在custom.conf里这个文件里的不能实现，
但是放到/etc/dnsmasq.d目录里是可以实现的。

我参考的是：https://github.com/shadowsocks/luci-app-shadowsocks/wiki/GfwList-Support
和 https://cokebar.info/archives/664 里的 “ China-List强制直连 自定义域名强制直连 ” 方法

**Comment by honwen** [comment]
LEDE 版本? OpenWRT 版本?

**Comment by Anyfc** [comment]
使用的是lede

**Comment by honwen** [comment]
```
现在在自定义列表里写下上面的规则后没有起到作用，
那么可否可以将自定义列表custom.conf这个文件移动到/etc/dnsmasq.d 以达到同样的效果？
```

这个方案是应该是ok的，为什么现在不生效我之后再检查一下

**Comment by honwen** [comment]
LEDE 17.01.2
ip.gs 在HK
MODE=ChnRoute

```ipset=/.ip.gs/ssr_spec_dst_bp```


测试ip.gs没走代理

**Comment by Anyfc** [comment]
呃~可能我的表述不是很清楚。
我的意思是：直接将 custom.conf这个文件移动到/etc/dnsmasq.d 后是可以生效的，但是在luci下编辑的却是/etc/dnsmasq-extra.d里面的custom.conf

**Comment by honwen** [comment]
See:

https://github.com/chenhw2/openwrt-dnsmasq-extra/blob/master/dnsmasq-extra/files/dnsmasq-extra.init#L63

**Comment by Anyfc** [comment]
奇怪， ipset=/.ip.gs/ssr_spec_dst_bp 放到/etc/dnsmasq-extra.d下，一开始的时候显示国内ip，刷新几次之后就变成代理ip
但是放到/etc/dnsmasq.d 却是很稳定的显示国内ip

我还是继续放到/etc/dnsmasq.d好了

**Comment by honwen** [comment]
你可以试试这个版本的

**Comment by Anyfc** [comment]
感谢，使用新版本openwrt-dnsmasq-extra，测试ip.gs稳定没走代理
