### ISSUE TITLE
It's slow while switching s-s account

### ISSUE THREAD

**Issue by jack338c** [chenhw2/luci-app-shadowsocksr#6]
Hi,Chen
long time no see, It's glad to see your repository again ,It's my favorite 
Recenlty I found  it's slow while  switching  multi-s-s account,Espeically when some of account  is not available or it can not be ping

Could you give me some ideas
thank you

**Comment by honwen** [comment]
Switch server, means restart ssr (meanwhile restart dnsmasq, cron), this may case overhead.

And I had modify [ssr-rules](https://github.com/chenhw2/luci-app-shadowsocksr/blob/master/files/root/usr/bin/ssr-rules) to reload some firewall-plugin to **keep them work properly**.

[ssr-rules](https://github.com/chenhw2/luci-app-shadowsocksr/blob/master/files/root/usr/bin/ssr-rules) only ```ping -4 t.cn``` to wait for dnsmasq ready.

**Comment by jack338c** [comment]
@chenhw2 
Ok, I got it
see you my idol

**Comment by honwen** [comment]
Thanks
