### ISSUE TITLE
如何配置gfwlist

### ISSUE THREAD

**Issue by kotori2** [chenhw2/luci-app-shadowsocksr#8]
表示真没看懂（

**Comment by honwen** [comment]
gfwlist 自动更新，无法配置

有需要就去改动 ```自定义列表```

**Comment by kotori2** [comment]
我读了下源码，启用GFWlist需要用到`dnsmasq-extra`这个包，但是我在官方源里面并没有找到，请问是您仓库里面的`https://github.com/chenhw2/openwrt-dnsmasq-extra`这个吗

**Comment by honwen** [comment]
对，这个仓库（```https://github.com/chenhw2/openwrt-dnsmasq-extra```）可以脱离SS(R)提供干净的DNS，所以独立开

**Comment by kotori2** [comment]
挺奇怪的，编译好并且安装了4个编译出来的ipk以后，全局代理正常，仅代理中国大陆无法访问的地址时无法打开twitter，chinadns模式能打开，但是使用`ip111.cn`检测IP的时候，访问国外地址的IP仍然是我本机IP？

**Comment by honwen** [comment]
你用什么路由

**Comment by kotori2** [comment]
K3+Lean大的LEDE

**Comment by honwen** [comment]
Lean有内置ipet-list, 跟dnsmasq-extra作用差不多，可能哪里冲突了吧

**Comment by kotori2** [comment]
emmm下课回来又测了下，发现gfwlist模式下用wget能打开页面
```wget twitter.com -4
--2017-11-23 17:51:49--  http://twitter.com/
正在解析主机 twitter.com (twitter.com)... 69.171.229.28
正在连接 twitter.com (twitter.com)|69.171.229.28|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 301 Moved Permanently
位置：https://twitter.com/ [跟随至新的 URL]
--2017-11-23 17:51:49--  https://twitter.com/
正在连接 twitter.com (twitter.com)|69.171.229.28|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度： 374048 (365K) [text/html]
index.html: 权限不够

无法写入 “index.html” (成功)。
```
可是用浏览器打开直接timeout

**Comment by honwen** [comment]
reboot everything, and then try again.

**Comment by kotori2** [comment]
噗重启大法

**Comment by kotori2** [comment]
Works！！！感谢

**Comment by honwen** [comment]
重启大法好
